targets:
  $default:
    builders:
      graphql_codegen:
        options:
          schema: lib/graphql/schema.graphql
          queries_glob: lib/graphql/queries.graphql
          output_dir: lib/graphql/__generated__
